import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import axios from "axios";
import "./globals.css";
import { signOut } from "@/auth";
import { authRoutes } from "@/routes";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

axios.defaults.baseURL = "http://localhost:3000";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
